#!/usr/bin/env bash
# coucou les coco
sed -i '/\slocalhost$/d' /etc/hosts
sed -i '/\sfacebook\.com$/d' /etc/hosts
echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts
